import { type Interest } from "~/types/interest";
import { type SimpleUser } from "~/types/user";
import { TaskType, type Task } from "~/types/task";
import { type Post } from "~/types/post";

export const defaultUser: SimpleUser = {
  id: "system",
  name: "System",
  displayName: "System",
  image: "v1745329655/profile-pictures/default",
};

export const defaultInterest: Interest = {
  id: -1,
  name: "Choose an interest",
  icon: "",
  colour: "",
  createdById: defaultUser.id,
  createdBy: defaultUser,
};

export const defaultTask: Task = {
  id: -1,
  type: TaskType.GENERATED,
  name: "",
  icon: "🔮",
  userId: "",
  friends: [],
  createdAt: new Date(),
  updatedAt: new Date(),
  interestIds: [],
  description: "",
  completed: false,
};

export const defaultPost: Post = {
  id: -1,
  name: "",
  task: defaultTask,
  description: "",
  createdAt: new Date(),
  updatedAt: new Date(),
  likedBy: [],
  imageUrl: "",
  comments: [],
  createdById: "",
  createdBy: defaultUser,
};

export const defaultInterests = [
  {
    id: 99999,
    name: "Self-care",
    icon: "🧘",
    colour: "#A3D2CA",
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
  {
    id: 100000,
    name: "Study",
    icon: "📚",
    colour: "#6C63FF",
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
  {
    id: 100001,
    name: "Fitness",
    icon: "🏋️",
    colour: "#FF6B6B",
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
  {
    id: 100002,
    name: "Social",
    icon: "👥",
    colour: "#4ECDC4",
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
  {
    id: 100003,
    name: "Travel",
    icon: "✈️",
    colour: "#00B4D8",
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
  {
    id: 100004,
    name: "Nature",
    icon: "🌳",
    colour: "#2E8B57",
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
  {
    id: 100005,
    name: "Business",
    icon: "💼",
    colour: "#3D3D3D",
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
  {
    id: 100006,
    name: "Dreams",
    icon: "💭",
    colour: "#B388EB",
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
  {
    id: 100007,
    name: "Food",
    icon: "🍔",
    colour: "#FF7F50",
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
  {
    id: 100008,
    name: "Health",
    icon: "💊",
    colour: "#EF476F",
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
  {
    id: 100009,
    name: "Family",
    icon: "👪",
    colour: "#F5B7B1",
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
  {
    id: 100010,
    name: "Friends",
    icon: "👫",
    colour: "#48CAE4",
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
  {
    id: 100011,
    name: "Home",
    icon: "🏠",
    colour: "#7FB069",
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
  {
    id: 100012,
    name: "Personal Growth",
    icon: "🧑‍🤝‍🧑",
    colour: "#CDB4DB",
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
  {
    id: 100013,
    name: "Finance",
    icon: "💰",
    colour: "#06D6A0",
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
  {
    id: 100014,
    name: "Education",
    icon: "🎓",
    colour: "#118AB2",
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
  {
    id: 100015,
    name: "Entertainment",
    icon: "🎭",
    colour: "#FFB4A2",
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
  {
    id: 100016,
    name: "Planning",
    icon: "🗓️",
    colour: "#6D6875",
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
  {
    id: 100017,
    name: "Organization",
    icon: "🗄️",
    colour: "#8D99AE",
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
  {
    id: 100018,
    name: "Appointments",
    icon: "📋",
    colour: "#FFD166",
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
  {
    id: 100019,
    name: "Meditation",
    icon: "🧘‍♂️",
    colour: "#B5E48C",
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
  {
    id: 100020,
    name: "Spirituality",
    icon: "🕯️",
    colour: "#F9C74F",
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
  {
    id: 100021,
    name: "Shopping",
    icon: "🛒",
    colour: "#FFADAD",
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
  {
    id: 100022,
    name: "Music",
    icon: "🎵",
    colour: "#9D4EDD",
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
  {
    id: 100023,
    name: "Cleaning",
    icon: "🧹",
    colour: "#90E0EF",
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
  {
    id: 100024,
    name: "Volunteering",
    icon: "🤝",
    colour: "#43AA8B",
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
  {
    id: 100025,
    name: "Pets",
    icon: "🐕",
    colour: "#FFB703",
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
  {
    id: 100026,
    name: "Art",
    icon: "🎨",
    colour: "#F4A261",
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
  {
    id: 100027,
    name: "Cooking",
    icon: "🍳",
    colour: "#F77F00",
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
  {
    id: 100028,
    name: "Celebration",
    icon: "🎉",
    colour: "#E5989B",
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
  {
    id: 100029,
    name: "Design",
    icon: "🎨",
    colour: "#FFD6A5",
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
  {
    id: 100030,
    name: "Sports",
    icon: "⚽",
    colour: "#48CAE4",
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
  {
    id: 100031,
    name: "Technology",
    icon: "💻",
    colour: "#00B4D8",
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
  {
    id: 100032,
    name: "Coding",
    icon: "👨‍💻",
    colour: "#6C63FF",
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
  {
    id: 100033,
    name: "Exploration",
    icon: "🧭",
    colour: "#219EBC",
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
  {
    id: 100034,
    name: "Fashion",
    icon: "👗",
    colour: "#FF9F1C",
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
  {
    id: 100035,
    name: "Style",
    icon: "🕶️",
    colour: "#E5989B",
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
  {
    id: 100036,
    name: "Gaming",
    icon: "🎮",
    colour: "#6A4C93",
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
  {
    id: 100037,
    name: "Streaming",
    icon: "📺",
    colour: "#9D4EDD",
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
  {
    id: 100038,
    name: "Photography",
    icon: "📷",
    colour: "#90E0EF",
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
  {
    id: 100039,
    name: "Reading",
    icon: "📖",
    colour: "#8D99AE",
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
  {
    id: 100040,
    name: "Writing",
    icon: "✍️",
    colour: "#F4A261",
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
  {
    id: 100041,
    name: "Crafting",
    icon: "✂️",
    colour: "#F7B267",
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
  {
    id: 100042,
    name: "DIY",
    icon: "🛠️",
    colour: "#5E6472",
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
  {
    id: 100043,
    name: "Outdoor Activities",
    icon: "🥾",
    colour: "#2E8B57",
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
  {
    id: 100044,
    name: "Community",
    icon: "🏘️",
    colour: "#6D6875",
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
  {
    id: 100045,
    name: "Entrepreneurship",
    icon: "🚀",
    colour: "#06D6A0",
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
  {
    id: 100046,
    name: "Content Creation",
    icon: "🎥",
    colour: "#FF7F50",
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
];
