import { type Interest } from "~/types/interest";
import { type SimpleUser } from "~/types/user";
import { type Task } from "~/types/task";
import { type Post } from "~/types/post";
import { TaskType } from "@prisma/client";

export const defaultUser: SimpleUser = {
  id: "system",
  displayName: "System",
  image: "v1745329655/profile-pictures/default",
};

export const defaultInterest: Interest = {
  id: -1,
  name: "Choose an interest",
  icon: "",
  colour: "",
  private: false,
  createdById: defaultUser.id,
  createdBy: defaultUser,
  users: [],
};

export const defaultTask: Task = {
  id: -1,
  type: TaskType.GENERATED,
  name: "",
  icon: "🔮",
  createdById: "system",
  friends: [],
  createdAt: new Date(),
  updatedAt: new Date(),
  interests: [],
  description: "",
  completed: false,
};

export const defaultPost: Post = {
  id: -1,
  name: "",
  task: defaultTask,
  description: "",
  createdAt: new Date(),
  updatedAt: new Date(),
  private: false,
  likedBy: [],
  imageUrl: "",
  comments: [],
  createdById: "",
  createdBy: defaultUser,
};

export const defaultInterests = [
  {
    id: 999999,
    name: "Self-care",
    icon: "🧘",
    colour: "#A3D2CA",
    private: false,
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
  {
    id: 1000000,
    name: "Study",
    icon: "📚",
    colour: "#6C63FF",
    private: false,
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
  {
    id: 1000001,
    name: "Fitness",
    icon: "🏋️",
    colour: "#FF6B6B",
    private: false,
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
  {
    id: 1000002,
    name: "Social",
    icon: "👥",
    colour: "#4ECDC4",
    private: false,
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
  {
    id: 1000003,
    name: "Travel",
    icon: "✈️",
    colour: "#00B4D8",
    private: false,
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
  {
    id: 1000004,
    name: "Nature",
    icon: "🌳",
    colour: "#2E8B57",
    private: false,
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
  {
    id: 1000005,
    name: "Business",
    icon: "💼",
    colour: "#3D3D3D",
    private: false,
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
  {
    id: 1000006,
    name: "Dreams",
    icon: "💭",
    colour: "#B388EB",
    private: false,
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
  {
    id: 1000007,
    name: "Food",
    icon: "🍔",
    colour: "#FF7F50",
    private: false,
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
  {
    id: 1000008,
    name: "Health",
    icon: "💊",
    colour: "#EF476F",
    private: false,
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
  {
    id: 1000009,
    name: "Family",
    icon: "👪",
    colour: "#F5B7B1",
    private: false,
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
  {
    id: 1000010,
    name: "Friends",
    icon: "👫",
    colour: "#48CAE4",
    private: false,
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
  {
    id: 1000011,
    name: "Home",
    icon: "🏠",
    colour: "#7FB069",
    private: false,
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
  {
    id: 1000012,
    name: "Personal Growth",
    icon: "🧑‍🤝‍🧑",
    colour: "#CDB4DB",
    private: false,
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
  {
    id: 1000013,
    name: "Finance",
    icon: "💰",
    colour: "#06D6A0",
    private: false,
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
  {
    id: 1000014,
    name: "Education",
    icon: "🎓",
    colour: "#118AB2",
    private: false,
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
  {
    id: 1000015,
    name: "Entertainment",
    icon: "🎭",
    colour: "#FFB4A2",
    private: false,
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
  {
    id: 1000016,
    name: "Planning",
    icon: "🗓️",
    colour: "#6D6875",
    private: false,
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
  {
    id: 1000017,
    name: "Organization",
    icon: "🗄️",
    colour: "#8D99AE",
    private: false,
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
  {
    id: 1000018,
    name: "Appointments",
    icon: "📋",
    colour: "#FFD166",
    private: false,
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
  {
    id: 1000019,
    name: "Meditation",
    icon: "🧘‍♂️",
    colour: "#B5E48C",
    private: false,
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
  {
    id: 1000020,
    name: "Spirituality",
    icon: "🕯️",
    colour: "#F9C74F",
    private: false,
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
  {
    id: 1000021,
    name: "Shopping",
    icon: "🛒",
    colour: "#FFADAD",
    private: false,
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
  {
    id: 1000022,
    name: "Music",
    icon: "🎵",
    colour: "#9D4EDD",
    private: false,
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
  {
    id: 1000023,
    name: "Cleaning",
    icon: "🧹",
    colour: "#90E0EF",
    private: false,
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
  {
    id: 1000024,
    name: "Volunteering",
    icon: "🤝",
    colour: "#43AA8B",
    private: false,
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
  {
    id: 1000025,
    name: "Pets",
    icon: "🐕",
    colour: "#FFB703",
    private: false,
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
  {
    id: 1000026,
    name: "Art",
    icon: "🎨",
    colour: "#F4A261",
    private: false,
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
  {
    id: 1000027,
    name: "Cooking",
    icon: "🍳",
    colour: "#F77F00",
    private: false,
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
  {
    id: 1000028,
    name: "Celebration",
    icon: "🎉",
    colour: "#E5989B",
    private: false,
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
  {
    id: 1000029,
    name: "Design",
    icon: "🎨",
    colour: "#FFD6A5",
    private: false,
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
  {
    id: 1000030,
    name: "Sports",
    icon: "⚽",
    colour: "#48CAE4",
    private: false,
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
  {
    id: 1000031,
    name: "Technology",
    icon: "💻",
    colour: "#00B4D8",
    private: false,
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
  {
    id: 1000032,
    name: "Coding",
    icon: "👨‍💻",
    colour: "#6C63FF",
    private: false,
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
  {
    id: 1000033,
    name: "Exploration",
    icon: "🧭",
    colour: "#219EBC",
    private: false,
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
  {
    id: 1000034,
    name: "Fashion",
    icon: "👗",
    colour: "#FF9F1C",
    private: false,
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
  {
    id: 1000035,
    name: "Style",
    icon: "🕶️",
    colour: "#E5989B",
    private: false,
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
  {
    id: 1000036,
    name: "Gaming",
    icon: "🎮",
    colour: "#6A4C93",
    private: false,
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
  {
    id: 1000037,
    name: "Streaming",
    icon: "📺",
    colour: "#9D4EDD",
    private: false,
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
  {
    id: 1000038,
    name: "Photography",
    icon: "📷",
    colour: "#90E0EF",
    private: false,
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
  {
    id: 1000039,
    name: "Reading",
    icon: "📖",
    colour: "#8D99AE",
    private: false,
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
  {
    id: 1000040,
    name: "Writing",
    icon: "✍️",
    colour: "#F4A261",
    private: false,
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
  {
    id: 1000041,
    name: "Crafting",
    icon: "✂️",
    colour: "#F7B267",
    private: false,
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
  {
    id: 1000042,
    name: "DIY",
    icon: "🛠️",
    colour: "#5E6472",
    private: false,
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
  {
    id: 1000043,
    name: "Outdoor Activities",
    icon: "🥾",
    colour: "#2E8B57",
    private: false,
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
  {
    id: 1000044,
    name: "Community",
    icon: "🏘️",
    colour: "#6D6875",
    private: false,
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
  {
    id: 1000045,
    name: "Entrepreneurship",
    icon: "🚀",
    colour: "#06D6A0",
    private: false,
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
  {
    id: 1000046,
    name: "Content Creation",
    icon: "🎥",
    colour: "#FF7F50",
    private: false,
    createdById: defaultUser.id,
    createdBy: defaultUser,
  },
];
